server.port=8082

spring.application.name=menu-order-service

spring.datasource.url=jdbc:h2:mem:menuorderdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=RafCafeSecretKeyForJwtTokenGeneration2024DevOnly
